name: dereference
version: 1.0.8
homepage: https://github.com/relf108
description: A sample command-line application.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  dcli: ^1.7.1
dev_dependencies: 
  pedantic: ^1.10.0
  test: ^1.16.0
executables: 
  dereference: 
